### ISSUE TITLE
Complete the incomplete selection

### ISSUE THREAD

**Issue by navakelvin** [antonk52/markdowny.nvim#10]
Can you implement that when a word or text is incompletely selected, the selection is completed sideways and then format? That is to say.

You have the following text:

`The sk<selection>y is blue and br<selection>ight` → `keybind format pressed` → `The <format><selection>sky is blue and bright<selection><format>`

The idea is not to have to select the text precisely for formatting, but instead to have nvim help you complete the selections.

Benefit: Edit faster on the fly.

**Comment by antonk52** [comment]
Thanks for the issue. As the initial idea behind this plugin was to have a similar experience to other non modal editors this change won't match with any of those programs(notion/reddit/github etc). Thus I think this change should not be made in this plugin.

Perhaps this can be done as a standalone plugin to increase visual selection with word boundaries.
