### ISSUE TITLE
Support Code-Block Surroundings

### ISSUE THREAD

**Issue by ful1e5** [antonk52/markdowny.nvim#4]
It would be nice to add a missing markdown code block (`text`) surrounding feature using the `<C-e>` keybind. However, fully supporting this feature would require some refactoring of the codebase, particularly for multi-line (V-LINE) selections, as well as changes to some utility functions. If you agree, I would be happy to open a pull request for it.

Thank you for creating such a great plugin.

**Comment by antonk52** [comment]
I love the suggestion. In fact I was not aware of this suggest.

Well happy to merge it if you want to send a PR 👍
